### ISSUE TITLE
Unable to start when defaulting to NVidia drivers in Optimus setup

### ISSUE THREAD

**Issue by KevinAtSesam** [Appadeia/taigo#4]
I found another issue related to the graphics. 

I'm running Fedora 31 on a Laptop with Optimus support, which means that I have both an Intel and a NVidia graphics card which are Frankensteined together. A few days ago, I had to run a graphical application that didn't do to well on the Intel GPU so I enabled[ NVidia PrimeGPU Support](https://rpmfusion.org/Howto/Optimus), which means I now default to the  NVidia GPU. Since that, I am no longer able to feed my Taigo :(

## Hardware 
See [previous issue](https://github.com/Appadeia/taigo/issues/3#issue-531845913)

## Stacktrace

```
(taigo:2): Clutter-CRITICAL **: 10:56:37.492: Unable to initialize Clutter: Unable to initialise the Clutter backend: no available drivers found.
false
Gtk-Message: 10:56:37.531: Failed to load module "pk-gtk-module"

(taigo:2): Clutter-WARNING **: 10:56:37.564: Missing Cogl context: was Clutter correctly initialized?

(taigo:2): Cogl-WARNING **: 10:56:37.622: Failed to create default context: Unable to create suitable GL context

** (taigo:2): CRITICAL **: 10:56:37.622: file ../src/taigochi.vala: line 154: uncaught error: Unable to load image data (clutter-image-error-quark, 0)

(taigo:2): Cogl-WARNING **: 10:56:37.671: Failed to create default context: Unable to create suitable GL context

** (taigo:2): CRITICAL **: 10:56:37.671: file ../src/taigochi.vala: line 136: uncaught error: Unable to load image data (clutter-image-error-quark, 0)

(taigo:2): Cogl-CRITICAL **: 10:56:37.789: cogl_xlib_renderer_get_visual_info: assertion 'cogl_is_renderer (renderer)' failed

(taigo:2): Clutter-WARNING **: 10:56:37.790: Missing Cogl context: was Clutter correctly initialized?

(taigo:2): Clutter-WARNING **: 10:56:37.790: Missing Cogl context: was Clutter correctly initialized?

[...] 
```

**Comment by rafaelmardojai** [comment]
I have the same issue on my Fedora 31 with NVidia drivers.

**Comment by sowelipililimute** [comment]
This issue should be resolved with the version of Taigo pending in the Flathub build queue. In the meantime, you can override the application permissions with `--device=dri`.

**Comment by KevinAtSesam** [comment]
Can confirm. The latest version of Taigo works again. Ow, how have I missed you, cute little Taikochi
