### ISSUE TITLE
Flatpak application lags

### ISSUE THREAD

**Issue by dschier-wtd** [Appadeia/taigo#5]
Hi,

thank you for the cool idea and your effort.
Unfortunately, the game is basically not playable on my machine.

it lags basically in every interaction and shows lots of delay for clicking something. Anyhow, I cannot see that it has huge load or stuff.

When starting the game via flatpak run, I am getting only one minor error:

```
~ $ flatpak run com.github.appadeia.Taigo 
libEGL warning: wayland-egl: could not open /dev/dri/card0 (No such file or directory)
false
```

I am running on Fedora 31, Wayland, Gnome-Shell.

Please reach out to me, if you need some more investigation or if I can support you in any way.

**Comment by sowelipililimute** [comment]
See #4
